name: Post standup order

on:
  schedule:
    # Runs at 06:28 Europe/London, Mon-Fri
    # GitHub's cron doesn't fire reliably, so intentionally
    # choose an earlier time to allow job to catch up and
    # run before 10 am
    - cron: '30 9 * * 1-5'
      timezone: 'Europe/London'
  workflow_dispatch:
      

jobs:
  post-order:
    runs-on: self-hosted
    steps:
      - name: Download latest binary
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release download latest --repo ${{ github.repository }} -p 'slack-standup-order-bot' -O bot
      - run: chmod +x bot
      - run: ./bot
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
